/* eslint-disable */
// scripts/seed-admin.js
// One-time seed: creates (or upgrades) a test ADMIN account so you can log into
// the new admin console.  Run from the backend folder:
//
//     node scripts/seed-admin.js
//
// Credentials created:
//     email:    test@test.com
//     password: test
//
// It reads DB settings from backend/.env (DB_HOST, DB_PORT, DB_USER, DB_PASS, DB_NAME)
// and writes a bcrypt hash of the password into the `users` table with role = 'Admin'.
// It also best-effort inserts a matching row into the `admins` table so the account
// shows up under "Admin Accounts" in the UI.

const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '..', '.env') });

const { Client } = require('pg');
const bcrypt = require('bcrypt');
const { randomUUID } = require('crypto');

const EMAIL = 'test@test.com';
const PASSWORD = 'test';
const USERNAME = 'testadmin';

async function main() {
  const client = new Client({
    host: process.env.DB_HOST || '127.0.0.1',
    port: Number(process.env.DB_PORT || 5432),
    user: process.env.DB_USER || 'postgres',
    password: process.env.DB_PASS,
    database: process.env.DB_NAME || 'enational_library',
  });

  await client.connect();
  console.log(`Connected to ${client.database} @ ${client.host}:${client.port}`);

  const passwordHash = await bcrypt.hash(PASSWORD, 10);

  // ── 1. Upsert the user (role Admin, status Active) ──────────────────────────
  const existing = await client.query('SELECT "userId" FROM "users" WHERE "email" = $1', [EMAIL]);

  let userId;
  if (existing.rows.length > 0) {
    userId = existing.rows[0].userId;
    await client.query(
      `UPDATE "users"
         SET "username" = $2, "passwordHash" = $3, "role" = 'Admin', "status" = 'Active'
       WHERE "userId" = $1`,
      [userId, USERNAME, passwordHash],
    );
    console.log(`Updated existing user ${EMAIL} -> Admin (userId ${userId})`);
  } else {
    userId = randomUUID();
    await client.query(
      `INSERT INTO "users"
         ("userId", "username", "gender", "email", "passwordHash", "phoneNumber", "role", "status")
       VALUES ($1, $2, 'Male', $3, $4, NULL, 'Admin', 'Active')`,
      [userId, USERNAME, EMAIL, passwordHash],
    );
    console.log(`Created new admin user ${EMAIL} (userId ${userId})`);
  }

  // ── 2. Best-effort: matching row in the `admins` table ──────────────────────
  // The OneToOne join column name is generated by TypeORM (usually "userUserId").
  // We look it up dynamically so this works regardless of the exact name.
  try {
    const cols = await client.query(
      `SELECT column_name FROM information_schema.columns WHERE table_name = 'admins'`,
    );
    const colNames = cols.rows.map((r) => r.column_name);
    const fkCol = colNames.find((c) => c !== 'userId'); // the FK to users

    if (!fkCol) {
      console.log('Could not detect admins FK column — skipping admins row (login still works).');
    } else {
      const already = await client.query(
        `SELECT 1 FROM "admins" WHERE "${fkCol}" = $1`,
        [userId],
      );
      if (already.rows.length === 0) {
        await client.query(
          `INSERT INTO "admins" ("userId", "${fkCol}") VALUES ($1, $2)`,
          [randomUUID(), userId],
        );
        console.log(`Linked admins row via "${fkCol}".`);
      } else {
        console.log('admins row already present.');
      }
    }
  } catch (e) {
    console.log('Skipped admins-table link (not required for login):', e.message);
  }

  await client.end();
  console.log('\n✅ Done. Log in with:');
  console.log('   email:    test@test.com');
  console.log('   password: test');
}

main().catch((err) => {
  console.error('Seed failed:', err.message);
  process.exit(1);
});
